/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PixelType implements org.apache.thrift.TEnum {
  Bool(1),
  Byte(2),
  Integer16(3),
  Integer32(4),
  Integer64(5),
  Double(6),
  Binary(7);

  private final int value;

  private PixelType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PixelType findByValue(int value) { 
    switch (value) {
      case 1:
        return Bool;
      case 2:
        return Byte;
      case 3:
        return Integer16;
      case 4:
        return Integer32;
      case 5:
        return Integer64;
      case 6:
        return Double;
      case 7:
        return Binary;
      default:
        return null;
    }
  }
}
