// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AddImageFilter.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace thrift;

class AddImageFilterHandler : virtual public AddImageFilterIf {
 public:
  AddImageFilterHandler() {
    // Your initialization goes here
  }

  void execute(Image& _return, const Image& image1, const Image& image2) {
    // Your implementation goes here
    printf("execute\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AddImageFilterHandler> handler(new AddImageFilterHandler());
  shared_ptr<TProcessor> processor(new AddImageFilterProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

