/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "image_constants.h"

namespace thrift {

const imageConstants g_image_constants;

imageConstants::imageConstants() {
}

} // namespace

