/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef image_CONSTANTS_H
#define image_CONSTANTS_H

#include "image_types.h"

namespace thrift {

class imageConstants {
 public:
  imageConstants();

};

extern const imageConstants g_image_constants;

} // namespace

#endif
